version: '3'
services:
  # api:
  #   container_name: api-github
  #   build: .
  #   ports:
  #     - "3010:3005"
  mongo:
    container_name: mongo-github
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/apidoc.json:/apidoc.json
    environment:
      SWAGGER_JSON: /apidoc.json
      # API_URL: ""
volumes:
  mongodata:
  data: